config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :templates
  resources :subject_data
  resources :options
  resources :subjects
  resources :uploads
  resources :members
  devise_for :users
  root "subjects#index"

end

app/views/templates/_form.html.erb
<%= simple_form_for(@template) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :thumbnail %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing Template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Templates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Thumbnail</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.name %></td>
        <td><%= template.thumbnail %></td>
        <td><%= template.description %></td>
        <td><%= link_to 'Show', template %></td>
        <td><%= link_to 'Edit', edit_template_path(template) %></td>
        <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<h1>New Template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @template.name %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= @template.thumbnail %>
</p>

<p>
  <strong>Description:</strong>
  <%= @template.description %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>