config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :templates
  resources :subject_data
  resources :options
  resources :subjects
  resources :uploads
  resources :members
  devise_for :users
  root "subjects#index"

end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :subject
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: [:show, :edit, :update, :destroy]

  # GET /options
  # GET /options.json
  def index
    @options = Option.all
  end

  # GET /options/1
  # GET /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(option_params)

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render :show, status: :created, location: @option }
      else
        format.html { render :new }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { render :show, status: :ok, location: @option }
      else
        format.html { render :edit }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to options_url, notice: 'Option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_params
      params.require(:option).permit(:title, :subject_id, :thumb, :select_counts)
    end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_form.html.erb
  <h3>Add new option</h3>
<%= simple_form_for(@option, html: { class: 'form-horizontal'}) do |f| %>
  <%= f.input :subject_id, :as => 'hidden', :value => @subject.id %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>
      <ul>
      <% @option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title %>
  <%= render :partial => '/uploads/basic', :locals => {:type => 'option'} %>
  <%= f.input :thumb, :as => 'hidden' %>
  <div class="form-group">
    <%= f.label :select_counts %><br>
    <%= f.number_field :select_counts %>
  </div>
  <div class="form-group">
    <%= f.submit :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/options/_list.html.erb
  <h3>Option items</h3>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Thumb</th>
      <th>Select counts</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @options.each do |option| %>
      <tr>
        <td><%= option.title %></td>
        <td><%= option.thumb %></td>
        <td><%= option.select_counts %></td>
        <td><%= link_to 'Show', option %></td>
        <td><%= link_to 'Edit', edit_option_path(option) %></td>
        <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/options/edit.html.erb
<h1>Editing Option</h1>

<%= render 'form' %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Options</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Subject</th>
      <th>Thumb</th>
      <th>Select counts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @options.each do |option| %>
      <tr>
        <td><%= option.title %></td>
        <td><%= option.subject %></td>
        <td><%= option.thumb %></td>
        <td><%= option.select_counts %></td>
        <td><%= link_to 'Show', option %></td>
        <td><%= link_to 'Edit', edit_option_path(option) %></td>
        <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<h1>New Option</h1>

<%= render 'form' %>

<%= link_to 'Back', options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @option.title %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @option.subject %>
</p>

<p>
  <strong>Thumb:</strong>
  <%= @option.thumb %>
</p>

<p>
  <strong>Select counts:</strong>
  <%= @option.select_counts %>
</p>

<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>