config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :templates
  resources :subject_data
  resources :options
  resources :subjects
  resources :uploads
  resources :members
  devise_for :users
  root "subjects#index"

end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :options
	has_one :subject_data,	dependent: :destroy,
							class_name: "SubjectDatum"
	belongs_to :user
	has_one :template
	has_one :style
end

app/controllers/subjects_controller.rb
class SubjectsController < UsersController
  # before_action :authenticate_user!
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
     @options = Option.where(subject: @subject)
     @option = Option.new
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
    @subject_datum = SubjectDatum.new
    #@subject.subject_datum.build
    @templates = Template.all.map{ |r| [r.name, r.id]}
    @styles = Style.all.map{ |r| [r.name, r.id]}
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)
  
    respond_to do |format|
      if @subject.save 
        @subject_data = SubjectDatum.new(subject_datum_params.merge(:subject_id => @subject.id))
        if @subject_data.save
          format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
          format.json { render :show, status: :created, location: @subject }
        else
          @subject.delete
          format.html { render :new }
          format.json { render json: @subject_data.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :user_id, :topic)
    end

    def subject_datum_params
      params.require(:subject).require(:subject_datum).permit(:topic_img, :description, :start_time, :end_time, :type)
    end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<!-- widget grid -->
<section id="widget-grid" class="">

  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- row -->
  <div class="row">
    <!-- NEW WIDGET START -->
    <article class="col-sm-12 col-md-12 col-lg-12">
        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget " id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false">
          <!-- widget options:
          usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
  
          data-widget-colorbutton="false"
          data-widget-editbutton="false"
          data-widget-togglebutton="false"
          data-widget-deletebutton="false"
          data-widget-fullscreenbutton="false"
          data-widget-custombutton="false"
          data-widget-collapsed="true"
          data-widget-sortable="false"
  
          -->
          <header role="heading">
            <span class="widget-icon"> <i class="fa fa-eye"></i> </span>
            <h2>创建主题&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h2>
            <ul class="nav nav-tabs pull-middle" id="widget-tab-1">
        
              <li class="active">
  
                <a href="#subject-main" data-toggle="tab"> <i class="fa fa-lg fa-arrow-circle-o-down"></i> <span class="hidden-mobile hidden-tablet"> 主题信息 </span> </a>
  
              </li>
  
              <li class="">
                <a href="#option-main" data-toggle="tab"> <i class="fa fa-lg fa-arrow-circle-o-up"></i> <span class="hidden-mobile hidden-tablet"> 投票选项 </span></a>
              </li>
  
            </ul>
            <span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span>
          </header>
          <!-- widget div-->
          <div role="content">
  
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->
  
            </div>
            <!-- end widget edit box -->
  
            <!-- widget content -->
            <div class="widget-body">
              <div class="tab-content padding-10">
                <div class="tab-pane fade active in" id="subject-main">
                <%= simple_form_for(@subject, html: { class: 'form-horizontal'}, defaults: { input_html: { class: 'form-control'}, lable_html: { class: 'col-md-2 control-label' } }) do |f| %>
                  <fieldset>
                        <legend>基本信息</legend>
                        <div class="form-group">
                          <label class="col-md-2 control-label">主题名称</label>
                          <div class="col-md-10">
                            <%= f.input_field :name %>
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="col-md-2 control-label">主题类别</label>
                          <div class="col-md-10">
                              <label class="checkbox-inline">
                                  <input type="checkbox" class="checkbox style-0">
                                  <span>教育</span>
                              </label>
                              <label class="checkbox-inline">
                                  <input type="checkbox" class="checkbox style-0">
                                  <span>金融</span>
                              </label>
                              <label class="checkbox-inline">
                                  <input type="checkbox" class="checkbox style-0">
                                  <span>电商</span>
                              </label>
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="col-md-2 control-label">主题模板</label>
                          <div class="col-md-10">
                            <%= f.input_field :template_id, collection: @templates, prompt: "Choose a Template",  selected: @subject.template_id %>
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="col-md-2 control-label">主题风格</label>
                          <div class="col-md-10">
                            <%= f.input_field :style_id, collection: @styles, prompt: "Choose a Style", selected: @subject.style_id  %>
                            
                            <div class="radio">
                                <label>
                                  <input type="radio" class="radiobox style-0" checked="checked" name="style-0">
                                  <span>Radiobox 1</span> 
                                </label>
                            </div>

                          </div>
                        </div>

                         <div class="form-group">
                          <label class="col-md-2 control-label">主题封面图片</label>
                          <div class="col-md-10">
                            <%= render :partial => '/uploads/basic' %>
                          </div>
                        </div>
                      
                      </fieldset>

                      <div class="form-actions">
                          <div class="row">
                            <div class="col-md-12">
                              <button class="btn btn-default" type="submit">
                                Cancel
                              </button>
                              <button class="btn btn-primary" type="submit">
                                <i class="fa fa-save"></i>
                                Submit
                              </button>
                            </div>
                          </div>
                        </div>
          
                    <% end %>
                  </div>

                  <div class="tab-pane fade" id="option-main">
                      <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>First Name</th>
                          <th>Last Name</th>
                          <th>Username</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>1</td>
                          <td>Mark</td>
                          <td>Otto</td>
                          <td>@mdo</td>
                        </tr>
                        <tr>
                          <td>2</td>
                          <td>Jacob</td>
                          <td>Thornton</td>
                          <td>@fat</td>
                        </tr>
                        <tr>
                          <td>3</td>
                          <td>Larry</td>
                          <td>the Bird</td>
                          <td>@twitter</td>
                        </tr>
                        <tr>
                          <td>4</td>
                          <td>Wise</td>
                          <td>Man</td>
                          <td>@myorange</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>

                </div>
            </div>

        </div>

      </div>
    </article>
  </div>

</section>


<script>

$(".form_datetime").datetimepicker({format: 'yyyy-mm-dd hh:ii'});

</script>

app/views/subjects/edit.html.erb
<!-- RIBBON -->
<div id="ribbon">

	<span class="ribbon-button-alignment"> <span id="refresh" class="btn btn-ribbon" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true"><i class="fa fa-refresh"></i></span> </span>

	<!-- breadcrumb -->
	<ol class="breadcrumb">
		<li>
			投票主题
		</li>
		<li>
			修改主题
		</li>
	</ol>
	<!-- end breadcrumb -->

	<!-- You can also add more buttons to the
	ribbon for further usability

	Example below:

	<span class="ribbon-button-alignment pull-right">
	<span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
	<span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
	<span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
	</span> -->

</div>
<!-- END RIBBON -->
<!-- MAIN CONTENT -->
<div id="content">

<%= render 'form' %>
</div>
<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<!-- RIBBON -->
<div id="ribbon">

  <span class="ribbon-button-alignment"> <span id="refresh" class="btn btn-ribbon" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true"><i class="fa fa-refresh"></i></span> </span>

  <!-- breadcrumb -->
  <ol class="breadcrumb">
    <li>
      投票主题
    </li>
    <li>
      主题列表
    </li>
  </ol>
  <!-- end breadcrumb -->

  <!-- You can also add more buttons to the
  ribbon for further usability

  Example below:

  <span class="ribbon-button-alignment pull-right">
  <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
  <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
  <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
  </span> -->

</div>
<!-- END RIBBON -->
<!-- MAIN CONTENT -->
<div id="content">

  <!-- widget grid -->
  <section id="widget-grid" class="">

    <div class="well">
      <div class="input-group">
        <input class="form-control" type="text" placeholder="Search...">
        <div class="input-group-btn">
          <button class="btn btn-default btn-primary" type="button">
            <i class="fa fa-search"></i> 搜索
          </button>
        </div>
      </div>
    </div>


    <!-- row -->
    <div class="row">
      <!-- NEW WIDGET START -->
      <article class="col-sm-12 col-md-12 col-lg-12">
          <!-- Widget ID (each widget will need unique ID)-->
          <div class="jarviswidget jarviswidget-color-greenDark" id="wid-id-0" data-widget-fullscreenbutton="true" data-widget-colorbutton="false" data-widget-editbutton="false">
            <!-- widget options:
            usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
    
            data-widget-colorbutton="false"
            data-widget-editbutton="false"
            data-widget-togglebutton="false"
            data-widget-deletebutton="false"
            data-widget-fullscreenbutton="false"
            data-widget-custombutton="false"
            data-widget-collapsed="true"
            data-widget-sortable="false"
    
            -->
            <header>
              <div class="jarviswidget-ctrls" role="menu">
                 <a data-placement="bottom" title="" rel="tooltip" class="button-icon jarviswidget-fullscreen-btn" href="javascript:void(0);" data-original-title="Fullscreen"><i class="fa fa-resize-full "></i></a> 
              </div>
              <span class="widget-icon"> <i class="fa fa-eye"></i> </span>
              <h2>投票主题列表</h2>

            </header>
            <!-- widget div-->
            <div>
    
              <!-- widget edit box -->
              <div class="jarviswidget-editbox">
                <!-- This area used as dropdown edit box -->
    
              </div>
              <!-- end widget edit box -->
              <div class="widget-body-toolbar">
                      
                      <div class="row">
                        
                        <div class="col-xs-9 col-sm-5 col-md-5 col-lg-5">
                          <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-search"></i></span>
                            <input type="text" placeholder="Filter" id="prepend" class="form-control">
                          </div>
                        </div>
                        <div class="col-xs-3 col-sm-7 col-md-7 col-lg-7 text-right">
                          
                          <button class="btn btn-success">
                            <i class="fa fa-plus"></i> <span class="hidden-mobile">创建投票</span>
                          </button>
                          
                        </div>
                        
                      </div>
                      
                        
        
                    </div>

              <!-- widget content -->
              <div class="widget-body no-padding">
                <table class="table table-hover table-striped">
                    <thead>
                      <tr>
                        <th>主题名称</th>
                        <th>用户</th>
                        <th>主题类别</th>
                        <th>操作</th>
                      </tr>
                    </thead>
                    <tbody>
                       <% @subjects.each do |subject| %>
                        <tr>
                          <td><%= subject.name %></td>
                          <td><%= subject.user_id %></td>
                          <td><%= subject.topic %></td>
                          <td><%= link_to 'Show', subject %>
                          <%= link_to 'Edit', edit_subject_path(subject) %>
                          <%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>


              </div>

          </div>

        </div>
      </article>
    </div>

  </section>


  <%= link_to 'New Subject', new_subject_path %>
</div>

app/views/subjects/new.html.erb
<!-- RIBBON -->
<div id="ribbon">

	<span class="ribbon-button-alignment"> <span id="refresh" class="btn btn-ribbon" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true"><i class="fa fa-refresh"></i></span> </span>

	<!-- breadcrumb -->
	<ol class="breadcrumb">
		<li>
			投票主题
		</li>
		<li>
			创建主题
		</li>
	</ol>
	<!-- end breadcrumb -->

	<!-- You can also add more buttons to the
	ribbon for further usability

	Example below:

	<span class="ribbon-button-alignment pull-right">
	<span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
	<span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
	<span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
	</span> -->

</div>
<!-- END RIBBON -->
<!-- MAIN CONTENT -->
<div id="content">
	<%= render 'form' %>
</div>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @subject.user_id %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @subject.topic %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>
	<div class="option_items">
		<%= render :partial => "options/list" %>
	</div>
	<div class="option_new">
		<%= render :partial => "options/form" %>
	</div>